name: amazed

on: [push, pull_request]

env:
  EXECUTABLE: amazed

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check coding style
        run:
          docker run --rm --security-opt "label:disable" -i -v "$(pwd)":"/mnt/delivery" -v "$(pwd)":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports" ;
          cat coding-style-reports.log;
          .github/workflows/display_coding_style

  check_program:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Launch "make"
        run: make
        timeout-minutes: 2
      - name: Check banned functions
        run: .github/workflows/check_banned_functions amazed .github/workflows/authorized_functions.txt
      - name: Launch "make clean"
        run: make clean
      - name: Check program compilation
        run: .github/workflows/check_program_compilation ${{ env.EXECUTABLE }}
      - name: Launch "make tests_run"
        run: make tests_run
        timeout-minutes: 2
